version: 0.2
            
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore alinac/alinac.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output alinac/alinac.csproj
artifacts:
  files:
    - alinac/build_output/**/*
    - appspec.yml
    - InstallApp.ps1
    - RemoveApp.ps1